# The jobs in this workflow are necessary because they are configured as
# required checks on PRs. Each job actually has a corresponding "real" job
# definition in a different workflow file:
#
# codegen-ci.yml: Codegen Tests
# tssdk-ci.yml: Typescript Tests
# python-ci.yml: Python Tests
#
# By hard-coding passing jobs with the same name here every PR will satisfy the
# repo's "required checks" EXCEPT those that trigger the "real" job AND that
# "real" job fails.
#
# It will look a little confusing: any PR that triggers a corresponding "real"
# job will have duplicate check entries, one that passes (this noop job) and the
# "real" job that either passes or fails.
name: Noop CI
on:
  pull_request:

jobs:
  noop-codegen-results:
    name: Codegen Tests
    runs-on: ubuntu-latest
    steps:
      - run: exit 0

  noop-typescript-results:
    name: Typescript Tests
    runs-on: ubuntu-latest
    steps:
      - run: exit 0

  noop-python-results:
    name: Python Tests
    runs-on: ubuntu-latest
    steps:
      - run: exit 0

  noop-apix-results:
    name: APIX Tests
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
