name: Noop CI
on:
  # This workflow is intended to be manually run on a branch for which the
  # PR triggers no other CI workflow (and thus cannot trigger any of the
  # required jobs). Eg. docs, examples, new packages that don't have a CI
  # workflow setup yet.
  workflow_dispatch:

jobs:
  noop-test-results:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        name: Noop Codegen Tests
        with:
          route: POST /repos/{owner}/{repo}/check-runs
          owner: looker-open-source
          repo: sdk-codegen
          name: Codegen Tests
          head_sha: ${{ github.sha }}
          conclusion: success
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: octokit/request-action@v2.x
        name: Noop Python Tests
        with:
          route: POST /repos/{owner}/{repo}/check-runs
          owner: looker-open-source
          repo: sdk-codegen
          name: Python Tests
          head_sha: ${{ github.sha }}
          conclusion: success
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: octokit/request-action@v2.x
        name: Noop Typescript Tests
        with:
          route: POST /repos/{owner}/{repo}/check-runs
          owner: looker-open-source
          repo: sdk-codegen
          name: Typescript Tests
          head_sha: ${{ github.sha }}
          conclusion: success
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
