name: Python Publish to PYPI
on:
  release:
    types: published

  workflow_dispatch:
    inputs:
      ref:
        description: 'commit/tag/branch to release from'
        required: true

defaults:
  run:
    shell: bash
    working-directory: python/

jobs:
  publish:
    permissions:
      contents: read
    if: >
      (github.event.inputs) ||
      (startsWith(github.event.release.tag_name, 'looker_sdk') &&
      !github.event.release.draft &&
      !github.event.release.prerelease)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          ref: ${{ github.event.release.tag_name || github.event.inputs.ref }}
          persist-credentials: false

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.10'

      - name: Package release artifacts
        run: |
          pip install wheel
          python setup.py sdist bdist_wheel

      - uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }} # zizmor: ignore[use-trusted-publishing]
          packages_dir: python/dist/
