name: Python Publish to PYPI
on:
  release:
    types: [edited]

defaults:
  run:
    shell: bash
    working-directory: python/

jobs:
  publish:

    if: >
      startsWith(github.event.release.tag_name, 'looker_sdk') &&
      !github.event.release.draft &&
      !github.event.release.prerelease

    runs-on: ubuntu-latest

    steps:
      - name: Repo Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Package release artifacts
        run: |
          pip install wheel
          python setup.py sdist bdist_wheel

      - name: Publish to pypi
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          # TODO: remove repository_url to default to prod
          repository_url: https://test.pypi.org/legacy/
          packages_dir: python/dist/
