name: Send publish metrics to bigquery
on:
  release:
    types: published
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1.0.0
        with:
          credentials_json: ${{ secrets.GCP_AR_READER_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          create_credentials_file: true
          export_environment_variables: true

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.0

      - run: 'jq -c ''.release |
             {
               package_name: .name | split(" ")[0],
               name,
               tag_name,
               version: .tag_name | split("-v")[1],
               html_url,
               target_commitish,
               created_at,
               published_at,
               draft,
               prerelease
             }'' $GITHUB_EVENT_PATH > releases.json'
      - run: bq load --source_format=NEWLINE_DELIMITED_JSON metrics.releases releases.json
