name: Resources Index CI
on:
  pull_request:
    paths:
      - bin/looker-resources-index/**
      - docs/resources/**
      - .github/workflows/resources-ci.yml

  push:
    branches:
      - main
    paths:
      - bin/looker-resources-index/**
      - docs/resources/**
      - .github/workflows/resources-ci.yml

  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: bin/looker-resources-index

permissions:
  checks: write

jobs:
  analyzebuild:
    name: Analyze and Build
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa # 0.12.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Repo Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false

      - name: Install Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22.x

      - name: Install Dependencies
        run: |
          yarn install

      - name: Test and Analyze
        run: |
          yarn run analyze

      - name: Build
        run: |
          yarn run build

      - name: Check if missing changes to resources.json/resources-lock.json
        run: |
          git diff --exit-code ../../docs/resources
